export const UIAssetKeys = {
  backgrounds: {
    loginNight: 'bg_login_night',
    homeCamp: 'bg_home_camp',
    shopVillage: 'bg_shop_village',
    inventoryParchment: 'bg_inventory_parchment',
  },
  panels: {
    woodHeader: 'panel_wood_header',
    parchment: 'panel_parchment',
    parchmentCard: 'panel_parchment_card',
    dark: 'panel_dark',
    darkGlass: 'panel_dark_glass',
    bottomNav: 'panel_bottom_nav',
  },
  buttons: {
    yellow: 'btn_yellow',
    green: 'btn_green',
    blue: 'btn_blue',
    brown: 'btn_brown',
    red: 'btn_red',
    iconRound: 'btn_icon_round',
  },
  icons: {
    gold: 'icon_gold',
    purpleGem: 'icon_purple_gem',
    blueGem: 'icon_blue_gem',
    energy: 'icon_energy',
    paw: 'icon_paw',
    back: 'icon_back',
    close: 'icon_close',
    settings: 'icon_settings',
    lock: 'icon_lock',
    redDot: 'icon_red_dot',
    home: 'icon_nav_home',
    shop: 'icon_nav_shop',
    backpack: 'icon_nav_backpack',
    battle: 'icon_nav_battle',
    talent: 'icon_nav_talent',
    pet: 'icon_nav_pet',
  },
  items: {
    sword: 'weapon_sword_01',
    bow: 'weapon_bow_01',
    staff: 'weapon_staff_01',
    spear: 'weapon_spear_01',
    fishboneBow: 'weapon_fishbone_bow',
    chest: 'item_weapon_chest',
    petEgg: 'item_pet_egg',
    potion: 'item_energy_potion',
    enhanceStone: 'item_enhance_stone',
  },
  characters: {
    catHero: 'cat_hero_idle',
    catBattle: 'cat_hero_battle',
    catShop: 'cat_shop_hood',
  },
} as const;

export type UIAssetKeyGroup = keyof typeof UIAssetKeys;
